name: Pull Request
on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.sh Tests'
        run: ./build.sh Tests
